import type { Metadata } from "next";

import { getLiveRouteForSlug, type LiveRoute } from "@/lib/live-route-data";
import { getSiteUrl } from "@/lib/site-config";

export const SITE_NAME = "Roseville Dental Academy";

const FALLBACK_TITLE = `${SITE_NAME} | Dental Assisting & Certification Training`;
const FALLBACK_DESCRIPTION =
  "Roseville Dental Academy trains dental assistants and certifies dental teams in Roseville, California with hands-on classes for BLS/CPR, infection control, radiation safety, coronal polish, and sealants.";

export type BuildPageMetadataInput = {
  route?: LiveRoute;
  path?: string;
  title?: string;
  description?: string;
  noindex?: boolean;
  image?: string;
  imageAlt?: string;
  type?: "website" | "article" | "profile";
};

function canonicalPathFromRoute(route: LiveRoute): string {
  // Encoded-slash routes have a clean alias in route.aliases[0] (e.g.
  // /bls%2Fcpr-1 → /bls-cpr-1). Vercel permanently redirects the encoded form,
  // so always emit the alias as canonical.
  if (route.route.includes("%2F") && route.aliases?.length) {
    return route.aliases[0];
  }
  return route.aliases?.[0] ?? route.route;
}

function normalizePath(value: string) {
  if (!value) {
    return "/";
  }

  const withSlash = value.startsWith("/") ? value : `/${value}`;
  return withSlash;
}

export function buildPageMetadata(input: BuildPageMetadataInput = {}): Metadata {
  const siteUrl = getSiteUrl();
  const route = input.route;
  const canonicalPath = normalizePath(
    route ? canonicalPathFromRoute(route) : input.path ?? "/",
  );
  const title = input.title ?? route?.title ?? FALLBACK_TITLE;
  const description =
    input.description ?? route?.description ?? FALLBACK_DESCRIPTION;
  const noindex = input.noindex ?? route?.noindex ?? false;
  const ogType = input.type ?? "website";
  const url = `${siteUrl}${canonicalPath === "/" ? "" : canonicalPath}`;

  // Always emit og:image + twitter:image. The default points at the dynamic
  // route generated by app/opengraph-image.tsx; per-route overrides win.
  const ogImageUrl = input.image ?? "/opengraph-image";
  const ogImageAlt =
    input.imageAlt ??
    "Roseville Dental Academy — Dental Assisting and Certification Training in Roseville, California";
  const ogImages = [
    {
      url: ogImageUrl,
      width: 1200,
      height: 630,
      alt: ogImageAlt,
    },
  ];

  return {
    metadataBase: new URL(siteUrl),
    applicationName: SITE_NAME,
    title,
    description,
    alternates: {
      canonical: canonicalPath,
    },
    robots: {
      index: !noindex,
      follow: !noindex,
      googleBot: {
        index: !noindex,
        follow: !noindex,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    icons: {
      icon: "/assets/favicon.png",
      shortcut: "/assets/favicon.png",
      apple: "/assets/favicon.png",
    },
    openGraph: {
      type: ogType,
      url,
      siteName: SITE_NAME,
      title,
      description,
      locale: "en_US",
      images: ogImages,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImageUrl],
    },
  };
}

export function buildMetadataForSlug(slug?: string | string[]): Metadata {
  const route = getLiveRouteForSlug(slug);
  return buildPageMetadata({ route });
}
