import type {
  AuthPageData,
  CoursePageData,
  CtaLink,
  FeatureItem,
  FooterSection,
  GalleryGroup,
  HeroContent,
  NavGroup,
  ProgramCardData,
  RegistrationCourseOption,
  RequirementGroup,
  ReviewPhotoData,
  SignupInterestOption,
  SitePageDefinition,
  SocialLink,
  SplitSectionContent,
  StatCardData,
  TestimonialData,
} from "@/lib/site-types";
import { activeSitePromo } from "@/lib/site-promo";
