export const dynamic = "force-static";

const WEBSITE_SITEMAP =
  '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>http://rosevilledentalacademy.com/radiation-safety</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/front-office-program</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/faqs-1</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/bls%2Fcpr-1</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/meet-the-instructors</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/photos</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/sealants</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/coronal-polish</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/infection-control</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>1</priority></url><url><loc>http://rosevilledentalacademy.com/dental-assisting-program</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/m/login</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/m/reset</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/m/create</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url><url><loc>http://rosevilledentalacademy.com/m/create-account</loc><lastmod>2026-04-15</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url></urlset>';

export function GET() {
  return new Response(WEBSITE_SITEMAP, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
    },
  });
}
